In [1]:
import requests
import json
import pandas as pd
from tqdm import tqdm

In [3]:
total_df = pd.DataFrame()
api_key = '6a4f6575757039363834685968426e'

for i in tqdm(range(1,1273500,1000)):
    start_index = i
    end_index = i + 999
    url = 'http://openapi.seoul.go.kr:8088/{0}/json/tbLnOpendataRtmsV/{1}/{2}/'.format(api_key,start_index,end_index)
    
    response = requests.get(url)
    data = json.loads(response.text)
    data_df = pd.DataFrame(data['tbLnOpendataRtmsV']['row'])
    total_df = pd.concat([total_df,data_df])

100%|████████████████████████████████████████████████████████████████████████████| 1274/1274 [5:21:11<00:00, 15.13s/it]

In [4]:
total_df

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11530,구로구,10800,오류동,1,대지,0006,0244,J팰리스,...,18000,29.24,17.63,4.0,,,2011,연립다세대,중개거래,서울 성북구
1,2024,11560,영등포구,12600,양평동2가,1,대지,0043,0014,CO-OP Residence/오목교,...,7600,16.98,26.58,9.0,,,2004,오피스텔,중개거래,서울 영등포구
2,2024,11290,성북구,13300,정릉동,,,,,,...,55200,37.08,156.00,0.0,,,1985,단독다가구,중개거래,서울 양천구
3,2024,11680,강남구,10100,역삼동,1,대지,0781,0037,781-37,...,67000,44.85,25.88,3.0,,,2017,연립다세대,중개거래,서울 강남구
4,2024,11380,은평구,10800,역촌동,1,대지,0080,0070,더라온,...,35000,54.37,33.25,4.0,,,2019,연립다세대,중개거래,서울 마포구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2015,11215,광진구,10500,자양동,1,대지,0579,0000,우성1,...,38200,59.91,0.00,8.0,,,1988,아파트,,
996,2015,11230,동대문구,10500,답십리동,1,대지,0492,0004,답십리한화오벨리스크,...,11400,29.88,40.23,3.0,,,2004,오피스텔,,
997,2015,11560,영등포구,13200,신길동,1,대지,4656,0000,우성3,...,26500,53.24,0.00,9.0,,,1989,아파트,,
998,2015,11230,동대문구,11000,이문동,1,대지,0225,0000,대림e-편한세상,...,36000,59.96,0.00,14.0,,,2003,아파트,,
999,2015,11260,중랑구,10400,묵동,1,대지,0121,0037,우리타운,...,19000,61.50,28.68,3.0,,,2002,연립다세대,,

In [5]:
total_df.to_csv('./data/Real_estate_transaction_data.csv')

In [2]:
2547000/2

1273500.0

In [2]:
total_df = pd.DataFrame()
api_key = '6a4f6575757039363834685968426e'

for i in tqdm(range(1273501,2547000,1000)):
    start_index = i
    end_index = i + 999
    url = 'http://openapi.seoul.go.kr:8088/{0}/json/tbLnOpendataRtmsV/{1}/{2}/'.format(api_key,start_index,end_index)
    
    response = requests.get(url)
    data = json.loads(response.text)
    data_df = pd.DataFrame(data['tbLnOpendataRtmsV']['row'])
    total_df = pd.concat([total_df,data_df])

100%|████████████████████████████████████████████████████████████████████████████| 1274/1274 [5:30:32<00:00, 15.57s/it]

In [3]:
total_df.to_csv('./data/Real_estate_transaction_data2(공공데이터-1273501~).csv')